export const iconMap = {
	// RENAME — icon lama → nama baru CF Code
	"account_circle": "user_circle",
	"add_photo_alternate": "add_image",
	"arrow_back": "step_back",
	"autorenew": "recycle",
	"bayanaka": "nakaStudio",
	"chat_bubble": "comment",
	"clearclose": "close",
	"code": "console",
	"coffeecode": "cfCode",
	"color_lenspalette": "color_palette",
	"palette": "color_palette_outline",
	"colorize": "color_picker",
	"compare_arrows": "close_others",
	"document-add": "document_add",
	"document-error": "document_error",
	"document-remove": "document_remove",
	"document-text-outline": "document_text_outline"
	"file_downloadget_app": "download",
	"first_page": "close_left",
	"folder-add": "folder_add",
	"folder-remove": "folder_remove",
	"funnel": "filter",
	"historyrestore": "history",
	"last_page": "close_right",
	"linkinsert_link": "insert_link",
	"menu": "humberger_menu",
	"more_vert": "option",
	"play_arrow": "run",
	"power_settings_new": "cf_power",
	"save_alt": "install",
	"scale": "license",
	"settings": "settings_gear",
	"tune": "settings_tune",
	"warningreport_problem": "report_problem",
	"zap": "lightning",
};

//=======================================================

// Icon yang namanya TETAP — tidak perlu diubah

export const keepIcons = [
	"add",
	"apps",
	"attach_file",
	"cart",
	"check",
	"check_circle",
	"copy",
	"cut",
	"delete",
	"delete_outline",
	"discord",
	"documents",
	"edit",
	"error",
	"error_outline",
	"expand_less",
	"expand_more",
	"favorite",
	"file",
	"folder",
	"fullscreen",
	"github",
	"gmail",
	"googlechrome",
	"house",
	"home",
	"home_filled",
	"image",
	"info",
	"info_outline",
	"instagram",
	"keyboard_arrow_down",
	"keyboard_arrow_left",
	"keyboard_arrow_right",
	"keyboard_arrow_up",
	"lightbulb",
	"like",
	"like_solid"
	"logout",
	"paste",
	"person",
	"redo",
	"refresh",
	"search",
	"stars",
	"tag",
	"telegram",
	"text_format",
	"twitter",
	"undo",
	"update",
	"verified",
];

//======================================================================

// Icon baru yang perlu dibikin SVG + upload ke IcoMoon
export const newIcons = {
	"color": null,
	"folder_open": null,
	"save_as": null,
	"active_library": null,
	"edit_text": null,
	"select": null,
	"select_all": null,
	"repo": null,
	"filter_filled": null,
};
